{
  "on": { "branch": "master" },
  "language": "node_js",
  "os": ["linux"],
  "dist": "xenial",
  "node_js": ["stable"],
  "script": ["npm install", "npm run build", "npm test"],
  "deploy":
    [
      {
        "provider": "surge",
        "skip_cleanup": true,
        "domain": "modern-branch.surge.sh",
        "project": "./build/",
      },
    ],
}
